heat_template_version: 2020-10-10

parameters:
  flavor:
   type: string
   description: I am using the very_small flavor

  image:
    type: string
    description: This uses an ubuntu image 
  
      
  key_name:
    type: string
    description: Name of key-pair to be used for compute instance

resources:
  heat_network:
    type: OS::Neutron::Net
    properties:
      admin_state_up: true
      name: network2

  heat_network_subnet:
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: heat_network }
      cidr: "10.1.1.0/24"
      dns_nameservers: ["8.8.8.8"]
      gateway_ip: "10.1.1.1"
      ip_version: 4

  heat_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: { network: internet }
      name: router2

  heat_router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: heat_router }
      subnet: { get_resource: heat_network_subnet }

  heat_server_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: heat_network }
      fixed_ips:
        - subnet_id: { get_resource: heat_network_subnet }

  heat_server:
    type: OS::Nova::Server
    properties:
      name: ubuntuserver
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_param: key_name}
      networks:
        - port: { get_resource: heat_server_port}

  heat_server_public_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: "internet"

  heat_server_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: heat_server_public_ip }
      port_id: { get_resource: heat_server_port }

outputs:
  heat_server_public_ip:
    description: IP Address of the deployed heat_server instance
    value: { get_attr: [ heat_server_public_ip, floating_ip_address ]}   